name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Hello first"
        - name: list files
          run: ls
        - name: read file
          run: cat README.md