name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "Upload and Download files has happened using atcions" > filename.txt

        - name: Upload file
          uses: actions/upload-artifact@v4
          with:
            name: myfile
            path: filename.txt
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: download artifact
          uses: actions/download-artifact@v4
          with:
            name: myfile
        - name: read file
          run : cat filename.txt
    third_job:
        needs: [first_job,second_job]
        runs-on: ubuntu-latest
        steps:
        - name: print messages for third job
          run: echo "Hello third Job Messages"