name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Welcome message
          run: touch "Hello first" >> hello.txt

        - name: list files
          run: ls
          
        - name: read file
          run: cat README.md
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: print messages for second job
          run: echo "Hello Second Job Messages"
        - name: sleep for 30 second
          run : sleep 30
    third_job:
        needs: [first_job,second_job]
        runs-on: ubuntu-latest
        steps:
        - name: print messages for third job
          run: echo "Hello third Job Messages"